# Generated by Django 5.0.3 on 2024-04-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Направление работы', 'verbose_name_plural': 'Направления работы'},
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(choices=[('no_experience', 'Нет опыта'), ('more_1_year', 'Более 1 года'), ('more_3_years', 'Более 3 лет'), ('more_5_years', 'More than 5 years'), ('other_experience', 'Other experience')], default='no_experience', max_length=20, verbose_name='Опыт работы'),
        ),
    ]
