# Generated by Django 5.0.3 on 2024-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_specialization_options_alter_user_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
