# Generated by Django 5.0.3 on 2024-04-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('event_status', models.CharField(choices=[('on_time', 'По расписанию'), ('scheduled', 'Запланировано'), ('cancelled', 'Отменено')], max_length=20, verbose_name='Статус')),
                ('registration_status', models.CharField(choices=[('not_started', 'Регистрация еще не началась'), ('open', 'Идет регистрация'), ('closed', 'Регистрация закрыта')], max_length=20, verbose_name='Статус регистрации')),
                ('organizer_name', models.CharField(max_length=100, verbose_name='Название организатора')),
                ('organizer_contacts', models.CharField(max_length=100, verbose_name='Контакты организатора')),
                ('description', models.TextField(verbose_name='Описание')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала')),
                ('format', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн')], max_length=20, verbose_name='Формат')),
                ('participant_limit', models.PositiveIntegerField(verbose_name='Лимит участников')),
                ('location_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место проведения')),
                ('location_coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='Координаты места проведения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/image/', verbose_name='Обложка события')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('host_photo', models.ImageField(blank=True, null=True, upload_to='events/hosts/image/', verbose_name='Фото ведущего')),
                ('host_full_name', models.CharField(max_length=100, verbose_name='ФИО ведущего')),
                ('host_contacts', models.CharField(max_length=100, verbose_name='Контакты ведущего')),
                ('host_company', models.CharField(max_length=100, verbose_name='Компания ведущего')),
                ('host_position', models.CharField(max_length=100, verbose_name='Должность ведущего')),
                ('event_link', models.URLField(verbose_name='Ссылка на событие')),
                ('recording_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на запись')),
                ('recording_link_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начало срока ссылки записи')),
                ('recording_link_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Конец срока ссылки записи')),
                ('online_stream_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на онлайн-трансляцию')),
                ('online_stream_link_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начало срока ссылки трансляции')),
                ('online_stream_link_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Конец срока ссылки трансляции')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('approved', models.BooleanField(default=False, verbose_name='Регистрация подтверждена')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/photo/', verbose_name='Фотография')),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания')),
                ('contacts', models.CharField(max_length=100, verbose_name='Контакты')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='events/speakers/image/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Спикер',
                'verbose_name_plural': 'Спикеры',
            },
        ),
        migrations.CreateModel(
            name='Subevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('time', models.TimeField(verbose_name='Время начала')),
            ],
            options={
                'verbose_name': 'Часть программы события',
                'verbose_name_plural': 'Части программы события',
            },
        ),
    ]
