# Generated by Django 5.0.3 on 2024-04-06 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subevent',
            options={'verbose_name': 'Часть программы', 'verbose_name_plural': 'Части программы'},
        ),
        migrations.AlterField(
            model_name='subevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subevents', to='events.event', verbose_name='Мероприятие, в котором эта часть программы'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='time',
            field=models.TimeField(verbose_name='Время начала проведения части программы'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название части программы'),
        ),
    ]
