# Generated by Django 5.0.3 on 2024-04-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_subevent_options_alter_subevent_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='events/speakers/image/', verbose_name='Фото спикера')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя спикера')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия спикера')),
                ('company', models.CharField(max_length=100, verbose_name='Компания спикера')),
                ('contacts', models.CharField(max_length=100, verbose_name='Контакты спикера')),
                ('position', models.CharField(max_length=100, verbose_name='Должность спикера')),
            ],
            options={
                'verbose_name': 'Спикер',
                'verbose_name_plural': 'Спикеры',
            },
        ),
    ]
