# Generated by Django 5.0.3 on 2024-04-13 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='subevent',
            options={'verbose_name': 'Часть программы события', 'verbose_name_plural': 'Части программы события'},
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.URLField(verbose_name='Ссылка на событие'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('on_time', 'По расписанию'), ('scheduled', 'Запланировано'), ('cancelled', 'Отменено')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн')], max_length=20, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/image/', verbose_name='Обложка события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Координаты места проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='online_stream_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на онлайн-трансляцию'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recording_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на запись'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Событие, на которое регистрация'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, зарегистрировавшийся на событие'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='contacts',
            field=models.CharField(max_length=100, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='events/speakers/image/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subevents', to='events.event', verbose_name='Событие, в котором эта программа'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subevents', to='events.speaker', verbose_name='Спикер, участвующий в программе'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/photo/', verbose_name='Фотография')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event', verbose_name='Событие, к которому относится фотография')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
