# Generated by Django 5.0.3 on 2024-04-06 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='subevent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.subevent', verbose_name='Часть программы, в которой участвует спикер'),
            preserve_default=False,
        ),
    ]
