# Generated by Django 5.0.3 on 2024-04-16 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subevent',
            options={'verbose_name': 'Программа события', 'verbose_name_plural': 'Программы событий'},
        ),
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='events/banner/', verbose_name='Баннер события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на событие'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='Участник события'),
        ),
    ]
